/* 
 * File:   OBJDict.h
 * Author: Rick
 *
 * Created on April 10, 2017, 12:15 PM
 */

#ifndef OBJDICT_H
#define	OBJDICT_H


/*!
** @file   ObjDict.h
** @author CAN Festival -- NNP
** @date   OD File produced: 2011-05-21 12:20:34.445000
**
** @brief This file is generated by the NNP Tool -- Object Dictionary Editor, as 
** originally developed by CAN Festival and modified by the NNP Team. 
** Specific contents are detailed in Object Dictionary Template.
** Editor modification: 4/29/2010 -- rev 1.0.0 
**
** This ObjDict.h file is generated from NNPPowerModule.odnn
** 
*/  



/* Master node data structure */

extern char SIBFault;
extern char Fault_SIBFault;
extern char Fault_SensorValueFault;
extern char Fault_HighPowerFault;
extern char SensorAttr_SensorFiltering;
extern char SensorAttr_SensorSampleRate;
extern char SensorAttr_SensorType;
extern char  SensorSw ;

#endif	/* OBJDICT_H */

